### ISSUE TITLE
Entering incorrect details in the Sign up tab takes the user to the Log in tab

### ISSUE THREAD

**Issue by AbhilashG97** [amfoss/fosswebsite#246]
**Summary:** 

Entering incorrect details in the Sign up tab takes the user to the Log in tab. When the user enters any incorrect value in the input field(s), the user is taken to the Log in tab after the validation errors are displayed.

**Steps to reproduce:**
 
1. Go to the [Sign up](http://127.0.0.1:8000/accounts/signup/) page
1. Select the Sign up tab, and click on the Create Account button without filling any details.
1. The user is taken to the Log in tab

**Expected behavior:** 

The user should not be taken to the Log in tab, instead the user should only be shown the validation errors while still being present in the Sign Up tab. 

**Observed behavior:** 

Currently, when the user enters any incorrect input, the user is taken to the Log in tab after the validation errors are displayed.

**GIF:** 

![awesomescreenshot-2017-12-29t22-16-33-592z](https://user-images.githubusercontent.com/20839661/34448826-81d12bfc-ed17-11e7-9591-15565f234b51.gif)

**Comment by Aniketh01** [comment]
Fixed. Thankyou :)
