### ISSUE TITLE
Clicking on the Sign-up button after logging out takes the user to Log-in tab instead of the Sign-up tab

### ISSUE THREAD

**Issue by AbhilashG97** [amfoss/fosswebsite#247]
**Summary:** 

Clicking on the Sign-up button after logging out takes the user to Log-in tab instead of the Sign-up tab. When the user clicks on the sign-up button after logging out, the user should be directed to the Sign-up tab and not the Log-in tab. 

**Steps to reproduce:** 

1. Visit [this](http://127.0.0.1:8000/accounts/logout/) page
1. Click on the Sign-up button
1. Log-in tab is displayed instead of the Sign-up tab

**Expected behavior:** 

When the user clicks on the Sign-up button after logging out, the user should be directed to the Sign-up tab and not the Log-in tab.

**Observed behavior:** 

Currently, clicking on the Sign-up button after logging out takes the user to Log-in tab instead of the Sign-up tab. 

**GIF:** 

![awesomescreenshot-2017-12-29t20-59-52-478z](https://user-images.githubusercontent.com/20839661/34448866-edc8c374-ed17-11e7-8aa9-032587a59729.gif)

**Comment by Aniketh01** [comment]
Fixed. Thanks :D
