### ISSUE TITLE
No validation error is raised when the e-mail field is left empty 

### ISSUE THREAD

**Issue by AbhilashG97** [amfoss/fosswebsite#248]
**Summary:** 

No validation error is raised when the e-mail field is left empty in the password reset page of the registration app.  

**Steps to reproduce:** 

1. Go to [password-reset](http://127.0.0.1:8000/accounts/password_reset/) page
1. Leave the e-mail field input field blank
1. Click on the submit button

**Expected behavior:** 

Validation error should be raised when the user enters invalid input in the e-mail input field

**Observed behavior:** 

No validation error is raised, when the user enters invalid input in the e-mail field

**GIF:** 

![awesomescreenshot-2017-12-30t07-56-09-640z](https://user-images.githubusercontent.com/20839661/34452456-42265b6e-ed65-11e7-8b5d-0d956b04fffd.gif)

**Comment by Aniketh01** [comment]
Thanks, this has been fixed and committed :)
