### ISSUE TITLE
Project detail out of alignment.

### ISSUE THREAD

**Issue by rahulk98** [amfoss/fosswebsite#272]
![screen shot 2018-02-01 at 8 53 41 pm 2](https://user-images.githubusercontent.com/29195786/35686362-225813bc-0792-11e8-9415-98dd9622c813.png)

**Comment by abhishekbvs** [comment]
![screenshot from 2018-06-27 23-30-05](https://user-images.githubusercontent.com/32136294/41991136-154e55d0-7a62-11e8-8a8b-7e96e7f60571.png)

**Comment by abhishekbvs** [comment]
#319
