### ISSUE TITLE
Student search in add student not working

### ISSUE THREAD

**Issue by rahulk98** [amfoss/fosswebsite#273]
The search bar for adding students to a project is not working.

**Comment by Aniketh01** [comment]
Similar in profile_list page as well.

**Comment by abhishekbvs** [comment]
![screenshot from 2018-06-26 11-46-41](https://user-images.githubusercontent.com/32136294/41989620-8e3b3530-7a5d-11e8-91f3-162f154aab26.png)
![screenshot from 2018-06-27 22-36-06](https://user-images.githubusercontent.com/32136294/41989623-8e7ad0a0-7a5d-11e8-849a-530331f59a7c.png)
