### ISSUE TITLE
Login should redirect to the same page

### ISSUE THREAD

**Issue by Chirath02** [amfoss/fosswebsite#295]
**Summary:** 

After successful login, the page should not redirect to the home page.

**Steps to reproduce the issue:** 

1) Logout
2) Go here http://localhost:8000/club/
3) Login
4) Redirects to the home page.

**Expected behavior:** 

It should redirect to the http://localhost:8000/club/ page.

**Comment by Aniketh01** [comment]
Thanks for the raising this issue. This has been fixed and committed :)
