### ISSUE TITLE
Members page layout issue

### ISSUE THREAD

**Issue by chirathr** [amfoss/fosswebsite#296]
**Summary:** 

The layout of the member's page seems to be crammed together and aligned to the left.

**GIF/Screenshots:** 
![screenshot_20180215_205838](https://user-images.githubusercontent.com/9161520/36264895-f9e952da-1293-11e8-8f5f-29372d46aeca.png)

**Comment by cyclopaman** [comment]
This is due to the irregularity of the details provided by the club members. In some cards a short description is present along with links while in majority of the cards no details are added

**Comment by Aniketh01** [comment]
@cyclopaman Thanks for your insight :). Pull request fixing this layout issue would we greatly appreciated :)

**Comment by cyclopaman** [comment]
@Aniketh01 for fixing the issue either I need the complete data or I have to remove the existing data completely.

**Comment by gopavasanth** [comment]
This existing feature looks nice to me, Why to change into a particular order? Is this not looking good right now? should we make this formal appearance? I am not sure just shared my opinion.

**Comment by abhishekbvs** [comment]
![screenshot from 2018-06-25 17-52-51](https://user-images.githubusercontent.com/32136294/41850422-21d154b8-78a2-11e8-9dbc-225289e1800f.png)
