### ISSUE TITLE
Can't login to the website.

### ISSUE THREAD

**Issue by amrtanair** [amfoss/fosswebsite#302]
When I try to log on to the website, albeit with a wrong username/password, it displays a 403 forbidden error. The screenshot is attached. 
![screenshot from 2018-03-06 18-52-04](https://user-images.githubusercontent.com/16919437/37034848-a9295872-2170-11e8-956a-916c3f9442ed.png)
Loading the website on Ubuntu 16.04, Chrome browser.

**Comment by Chirath02** [comment]
This issue is fixed, it was because of the `CSRF_COOKIE_SECURE` being set to true on an http website. The site will be changed to https soon :)
