### ISSUE TITLE
No option to add or create a new workshop

### ISSUE THREAD

**Issue by chirathr** [amfoss/fosswebsite#361]
**Summary:** 

`/workshop` view should have an option to add a new workshop. This should be visible for only an Admin. There is an existing URL `/workshop/create` which seems to throw an error. 

**GIF/Screenshots:** 

![image](https://user-images.githubusercontent.com/9161520/45358012-b5fa0600-b5e5-11e8-9d68-45e8e475d1d6.png)

**Comment by rammanoj** [comment]
Assigned to Raghvendra Vijaya

**Comment by chirathr** [comment]
Assigned to Shobitha
